spring:
  application:
    name: CartService

  config:
    import: optional:configserver:http://localhost:8081

  cloud:
    config:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
